package template.baremetal;

import fileAnnotation.FileType;
import fileAnnotation.FileTypeAnno;
import java.util.Set;
import template.templateInterface.InitTemplate;

@FileTypeAnno(type = FileType.C_SOURCE)
@SuppressWarnings("all")
public class CircularFIFOTemplateSrc implements InitTemplate {
  private /* Set<Vertex> */Object typeVertexSet;
  
  public CircularFIFOTemplateSrc() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field SDFChannel is undefined"
      + "\nThe method findSDFChannelDataType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method findVertexByName(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nThe field CircularFIFOTemplateSrc.typeVertexSet refers to the missing type Vertex"
      + "\nvertexSet cannot be resolved"
      + "\nstream cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nconforms cannot be resolved"
      + "\nmap cannot be resolved"
      + "\nmap cannot be resolved"
      + "\ncollect cannot be resolved");
  }
  
  public String create() {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\r\\n\\t\\t\\r\\n\\t\\t\'\'\'\'"
      + "\nno viable alternative at input \'}\'"
      + "\nno viable alternative at input \'produce\'"
      + "\nextraneous input \'typeVertex\' expecting \')\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nmissing \'}\' at \'»\\r\\n\\t\\t\\t\\tÂ«\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\r\\n\\t\\r\\n\\t\\t\'\'\'\'"
      + "\nno viable alternative at input \'}\'"
      + "\nno viable alternative at input \'getFileName\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'isOneDimension\'"
      + "\nextraneous input \'v\' expecting \')\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'}\'"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method produce(Vertex) is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method produce(Object) is undefined"
      + "\nThe method or field Vertex is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field VertexTrait is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method isOneDimension(Vertex) is undefined"
      + "\nThe method getMaximumElems(Vertex) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method getMaximumElems(Vertex) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method getMaximumElems(Vertex) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method getMaximumElems(Vertex) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method getMaximumElems(Vertex) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method isOneDimension(Vertex) is undefined"
      + "\nThe method getMaximumElems(Vertex) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field override is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method isOneDimension(Object) is undefined"
      + "\nThe method or field Vertex is undefined"
      + "\nThe method getInnerType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field v is undefined"
      + "\nThe method findVertexByName(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field VertexTrait is undefined"
      + "\nDuplicate local variable typeVertex"
      + "\nType mismatch: cannot convert from boolean to String"
      + "\nType mismatch: cannot convert from boolean to String"
      + "\nThe field CircularFIFOTemplateSrc.typeVertexSet refers to the missing type Vertex"
      + "\nUnreachable expression."
      + "\nThe field CircularFIFOTemplateSrc.typeVertexSet refers to the missing type Vertex"
      + "\nThis expression is not allowed in this context, since it doesn\'t cause any side effects."
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\nhasTrait cannot be resolved"
      + "\nTYPING_DATATYPES_ARRAY cannot be resolved"
      + "\n! cannot be resolved"
      + "\n&& cannot be resolved"
      + "\n> cannot be resolved"
      + "\n&& cannot be resolved"
      + "\n< cannot be resolved"
      + "\nhasTrait cannot be resolved"
      + "\nTYPING_DATATYPES_ARRAY cannot be resolved");
  }
}
