package template.baremetal.uniprocessor;

import fileAnnotation.FileType;
import fileAnnotation.FileTypeAnno;
import template.templateInterface.InitTemplate;

@FileTypeAnno(type = FileType.C_SOURCE)
@SuppressWarnings("all")
public class SubsystemInitSrc implements InitTemplate {
  public String create() {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\r\\n\\t\\t}\\r\\n\\t\\t\'\'\'\'"
      + "\nno viable alternative at input \'}\'"
      + "\nno viable alternative at input \'String\'"
      + "\nno viable alternative at input \'externChannel\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\r\\n\\t\\t\'\'\'\'"
      + "\nno viable alternative at input \'override\'"
      + "\nno viable alternative at input \'getFileName\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'}\'"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method externChannel() is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field kÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method externChannel() is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field override is undefined"
      + "\nDuplicate local variable channel"
      + "\nDuplicate local variable channel"
      + "\nDuplicate local variable sdfname"
      + "\nUnreachable expression."
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved");
  }
}
