package template.baremetal.uniprocessor;

import fileAnnotation.FileType;
import fileAnnotation.FileTypeAnno;
import generator.Schedule;
import template.templateInterface.SubsystemTemplate;

@FileTypeAnno(type = FileType.C_SOURCE)
@SuppressWarnings("all")
public class SubsystemTemplateSrc implements SubsystemTemplate {
  public String create(final Schedule s) {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'init_subsystem\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nmissing \'}\' at \'»\\r\\nÂ«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nmismatched input \'}\' expecting \'ENDIF\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'FOR\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\r\\n\\t\\t\'\'\'\'"
      + "\nno viable alternative at input \'}\'"
      + "\nno viable alternative at input \'getFileName\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'}\'"
      + "\nThe method or field SDFComb is undefined"
      + "\nThe method or field sdfcombÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\n== cannot be resolved."
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method init_subsystem() is undefined"
      + "\nThe method initChannels() is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field Â is undefined"
      + "\nThe method findSDFChannelDataType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field SDFChannel is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method findSDFChannelDataType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field kÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field override is undefined"
      + "\nDuplicate local variable channel"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nThe field Generator.uniprocessorSchedule refers to the missing type Vertex"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nUnreachable expression."
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nvertexSet cannot be resolved"
      + "\nstream cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nconforms cannot be resolved"
      + "\ncollect cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\n&& cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\nsafeCast cannot be resolved"
      + "\nget cannot be resolved"
      + "\ngetNumOfInitialTokens cannot be resolved"
      + "\n!== cannot be resolved"
      + "\n&& cannot be resolved"
      + "\ngetNumOfInitialTokens cannot be resolved"
      + "\n> cannot be resolved"
      + "\ngetProperties cannot be resolved"
      + "\nget cannot be resolved"
      + "\nunwrap cannot be resolved"
      + "\ngetIdentifier cannot be resolved");
  }
}
