package template.uniprocessor.subsystem;

import java.util.Set;
import java.util.TreeMap;
import template.templateInterface.SubsystemTemplate;

@SuppressWarnings("all")
public class SubsystemSingleSrc implements SubsystemTemplate {
  private /* Set<Vertex> */Object sdfactorSet;
  
  private /* TreeMap<Integer, Vertex> */Object uniprocessorSchedule;
  
  public String savePath() {
    return "/tile/subsystem.c";
  }
  
  public String create(final /* Vertex */Object tile) {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'&\'"
      + "\nno viable alternative at input \'fifo_Â\'"
      + "\nno viable alternative at input \'sdfchannel\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'»\\r\\n\\t\\t\\treturn 0;\\r\\n\\t\\t\\t}\\t\\t\\r\\n\\t\\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\'\'\'\'"
      + "\nno viable alternative at input \'}\'"
      + "\nno viable alternative at input \'inithelp\'"
      + "\nextraneous input \'sdfchannel\' expecting \')\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'String\'"
      + "\nno viable alternative at input \'externChannel\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\r\\n\\t\\t\'\'\'\'"
      + "\nno viable alternative at input \'}\'"
      + "\nno viable alternative at input \'void\'"
      + "\nno viable alternative at input \'createUniprocessorSchedule\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'private\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'ArrayList\'"
      + "\nextraneous input \'actor\' expecting \')\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'}\'"
      + "\nVertex cannot be resolved to a type."
      + "\nThe method or field SDFActor is undefined"
      + "\nThe method or field IntegerValue is undefined"
      + "\nThe method or field IntegerValue is undefined"
      + "\nThe method createUniprocessorSchedule() is undefined"
      + "\nThe method or field sdfactorSetÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field integerValuesÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method externChannel() is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field Â is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method findSDFChannelDataType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method findSDFChannelDataType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field SDFChannel is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method inithelp(Object) is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field delayValueListÂ is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method findSDFChannelDataType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field delayÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field delayÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method findSDFChannelDataType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field kÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method write_fifo() is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field kÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field ENDÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method inithelp(Object) is undefined"
      + "\nThe method or field SDFChannel is undefined"
      + "\n< cannot be resolved."
      + "\n+ cannot be resolved."
      + "\nThe method or field def is undefined"
      + "\nThe method externChannel() is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field Â is undefined"
      + "\nThe method findSDFChannelDataType(ForSyDeSystemGraph, Object) is undefined for the type Class<Query>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\n== cannot be resolved."
      + "\nThe method or field Â is undefined"
      + "\nThe method or field typeÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method createUniprocessorSchedule() is undefined"
      + "\nThe method getFiringSlot(Vertex) is undefined"
      + "\n< cannot be resolved."
      + "\n+ cannot be resolved."
      + "\nThe method or field private is undefined"
      + "\nThe method or field def is undefined"
      + "\n< cannot be resolved."
      + "\nThe method getFiringSlot(Object) is undefined"
      + "\nThe method or field Vertex is undefined"
      + "\nThe method or field actor is undefined"
      + "\nDuplicate local variable channel"
      + "\nDuplicate local variable delayValueList"
      + "\nDuplicate local variable k"
      + "\nDuplicate local variable channel"
      + "\nDuplicate local variable sdfname"
      + "\nType mismatch: cannot convert from ArrayList<String> to String"
      + "\nType mismatch: cannot convert from ArrayList<Integer> to String"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nThe field SubsystemSingleSrc.sdfactorSet refers to the missing type Vertex"
      + "\nThe field SubsystemSingleSrc.uniprocessorSchedule refers to the missing type Vertex"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nUnreachable expression."
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nThe field Generator.model refers to the missing type ForSyDeSystemGraph"
      + "\nUnreachable expression."
      + "\nThe field SubsystemSingleSrc.uniprocessorSchedule refers to the missing type Vertex"
      + "\nThe field SubsystemSingleSrc.sdfactorSet refers to the missing type Vertex"
      + "\nThe field SubsystemSingleSrc.uniprocessorSchedule refers to the missing type Vertex"
      + "\nvertexSet cannot be resolved"
      + "\nstream cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nconforms cannot be resolved"
      + "\ncollect cannot be resolved"
      + "\nvertexSet cannot be resolved"
      + "\nstream cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nconforms cannot be resolved"
      + "\nmap cannot be resolved"
      + "\nsafeCast cannot be resolved"
      + "\nget cannot be resolved"
      + "\ncollect cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\nsafeCast cannot be resolved"
      + "\nget cannot be resolved"
      + "\ngetNumOfInitialTokens cannot be resolved"
      + "\n!== cannot be resolved"
      + "\n&& cannot be resolved"
      + "\ngetNumOfInitialTokens cannot be resolved"
      + "\n> cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetNumOfInitialTokens cannot be resolved"
      + "\n!== cannot be resolved"
      + "\n&& cannot be resolved"
      + "\ngetNumOfInitialTokens cannot be resolved"
      + "\n> cannot be resolved"
      + "\ngetProperties cannot be resolved"
      + "\nget cannot be resolved"
      + "\nunwrap cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\ngetNumOfInitialTokens cannot be resolved"
      + "\ngetProperties cannot be resolved"
      + "\nget cannot be resolved"
      + "\nunwrap cannot be resolved"
      + "\ngetIdentifier cannot be resolved"
      + "\nsize cannot be resolved"
      + "\nget cannot be resolved"
      + "\n> cannot be resolved"
      + "\ngetProperties cannot be resolved"
      + "\nget cannot be resolved"
      + "\n!== cannot be resolved"
      + "\nunwrap cannot be resolved");
  }
}
