package template.rtos;

import fileAnnotation.FileType;
import fileAnnotation.FileTypeAnno;
import template.templateInterface.InitTemplate;

@FileTypeAnno(type = FileType.C_SOURCE)
@SuppressWarnings("all")
public class StartTaskTemplateSrcRTOS implements InitTemplate {
  public String create() {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\t\\t\\t\\t\\r\\n\\t\\t\\t}\\r\\n\\t\\t\\t\\r\\n\\t\\t\'\'\'\'"
      + "\nno viable alternative at input \'}\'"
      + "\nno viable alternative at input \'getFileName\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'}\'"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field sdfnameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field sdfchannelSetÂ is undefined for the type Class<Generator>"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field kÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field nameÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field override is undefined"
      + "\nDuplicate local variable sdfchannel"
      + "\nDuplicate local variable sdfname"
      + "\nDuplicate local variable sdfchannel"
      + "\nDuplicate local variable actor"
      + "\nDuplicate local variable actor"
      + "\nDuplicate local variable name"
      + "\nDuplicate local variable actor"
      + "\nDuplicate local variable name"
      + "\nDuplicate local variable actor"
      + "\nDuplicate local variable name"
      + "\nUnreachable expression.");
  }
}
